### PR TITLE
added leaic schema

### PR DESCRIPTION
**Pull request by tommeagher**
Inspired by @eads, here's a schema for the [2005 Law Enforcement Agency Identifiers Crosswalk](http://www.icpsr.umich.edu/icpsrweb/NACJD/studies/4634) from the National Archive of Criminal Justice Data.

### CODE REVIEW

**Comment by onyxfish** [comment]
Thanks, Tom! Mind adding an row to the [index.csv](https://github.com/onyxfish/ffs/blob/master/index.csv) before I merge?

**Comment by tommeagher** [comment]
I added that row. Sorry I missed it the first time.

**Comment by onyxfish** [comment]
Long overdue, but now merged. Thanks!

**Comment by tommeagher** [comment]
Thanks, Chris!

**Pull request merged**
